#pragma once

enum PLAYER_ACTION_INDEX
{
	ACTION_MOVE_LL = 0,
	ACTION_MOVE_LU,
	ACTION_MOVE_UU,
	ACTION_MOVE_RU,
	ACTION_MOVE_RR,
	ACTION_MOVE_RD,
	ACTION_MOVE_DD,
	ACTION_MOVE_LD,
	ACTION_ATTACK_L_FIRST,
	ACTION_ATTACK_L_SECOND,
	ACTION_ATTACK_L_THIRD,
	ACTION_ATTACK_R_FIRST,
	ACTION_ATTACK_R_SECOND,
	ACTION_ATTACK_R_THIRD,
	ACTION_STAND_L,
	ACTION_STAND_R,
};

enum MovePixelIndex
{
	MOVE_X_PIXEL = 3,
	MOVE_Y_PIXEL = 2,
};

enum RANGE_LIMIT_INDEX
{
	RANGE_MOVE_TOP = 0,
	RANGE_MOVE_LEFT = 0,
	RANGE_MOVE_RIGHT = 6400,
	RANGE_MOVE_BOTTOM = 6400,

	//eRANGE_MOVE_TOP = 50,
	//eRANGE_MOVE_LEFT = 10,
	//eRANGE_MOVE_RIGHT = 630,
	//eRANGE_MOVE_BOTTOM = 470,
};

enum RANGE_INDEX
{
	ERROR_RANGE = 50,
	ATTACK_RANGE = 60,
};

enum SECTOR_INDEX
{
	SECTOR_MAX_Y = 50,
	SECTOR_MAX_X = 50,
};

enum LOG_INDEX
{
	LOG_LEVEL_DEBUG = 0,
	LOG_LEVEL_WARNING,
	LOG_LEVEL_ERROR,
};
